export type PermissionRisk = 'standard' | 'sensitive' | 'critical';

export interface PermissionDefinition {
  key: string;
  category: string;
  resource: string;
  action: string;
  description: string;
  riskLevel: PermissionRisk;
  displayOrder: number;
  fields?: Readonly<Record<string, string>>;
  supportsApproval?: boolean;
  requiredEntitlement?: string;
  quotaKey?: string;
}

const permission = <const T extends PermissionDefinition>(definition: T) =>
  definition;

const PROFILE_FIELDS = {
  username: 'Username',
  name: 'Business name',
  phone: 'Phone number',
  logo: 'Business logo',
  favicon: 'Browser favicon',
  default_avatar: 'Default page avatar',
  website_color: 'Website color',
} as const;

const DEFAULT_FIELDS = {
  default_footer_text: 'Default footer text',
  default_footer_phone: 'Default footer phone',
  default_template: 'Default template',
  default_background_color: 'Default background color',
  default_footer_hidden: 'Hide footer by default',
  default_whatsapp_enabled: 'Enable WhatsApp modal by default',
} as const;

const LINKTREE_FIELDS = {
  name: 'Page name',
  subtitle: 'Page subtitle',
  subtitle_color: 'Subtitle color',
  description: 'Page description',
  seo_name: 'SEO name',
  image: 'Page image',
  background_color: 'Background color',
  template_config: 'Template configuration',
  footer_text: 'Footer text',
  footer_phone: 'Footer phone',
  footer_hidden: 'Footer visibility',
  whatsapp_modal: 'WhatsApp modal',
  status: 'Page status',
  is_campaign_active: 'Campaign active status',
  is_archived: 'Archive status',
} as const;

const LINK_FIELDS = {
  platform: 'Platform',
  url: 'URL',
  display_name: 'Display name',
  description: 'Description',
  default_message: 'Default message',
  display_order: 'Display order',
  metadata: 'Link metadata',
} as const;

const ALL_PERMISSION_DEFINITIONS = [
  permission({
    key: 'business:dashboard:view',
    category: 'Business navigation',
    resource: 'business.dashboard',
    action: 'view',
    description: 'Open the business dashboard',
    riskLevel: 'standard',
    displayOrder: 10,
  }),
  permission({
    key: 'business:pages:linktrees-access',
    category: 'Business navigation',
    resource: 'business.pages',
    action: 'linktrees-access',
    description: 'Open the linktrees page',
    riskLevel: 'standard',
    displayOrder: 11,
  }),
  permission({
    key: 'business:pages:templates-access',
    category: 'Business navigation',
    resource: 'business.pages',
    action: 'templates-access',
    description: 'Open the templates page',
    riskLevel: 'standard',
    displayOrder: 12,
  }),
  permission({
    key: 'business:pages:profile-access',
    category: 'Business navigation',
    resource: 'business.pages',
    action: 'profile-access',
    description: 'Open the business profile page',
    riskLevel: 'standard',
    displayOrder: 13,
  }),
  permission({
    key: 'business:pages:settings-access',
    category: 'Business navigation',
    resource: 'business.pages',
    action: 'settings-access',
    description: 'Open the business settings page',
    riskLevel: 'standard',
    displayOrder: 14,
  }),
  permission({
    key: 'business:pages:advertising-access',
    category: 'Business navigation',
    resource: 'business.pages',
    action: 'advertising-access',
    description: 'Open the advertising page',
    riskLevel: 'standard',
    displayOrder: 20,
  }),
  permission({
    key: 'business:settings:profile-access',
    category: 'Business navigation',
    resource: 'business.settings',
    action: 'profile-access',
    description: 'Open the profile settings section',
    riskLevel: 'standard',
    displayOrder: 15,
  }),
  permission({
    key: 'business:settings:defaults-access',
    category: 'Business navigation',
    resource: 'business.settings',
    action: 'defaults-access',
    description: 'Open the page defaults settings section',
    riskLevel: 'standard',
    displayOrder: 16,
  }),
  permission({
    key: 'business:settings:security-access',
    category: 'Business navigation',
    resource: 'business.settings',
    action: 'security-access',
    description: 'Open the account security settings section',
    riskLevel: 'standard',
    displayOrder: 17,
  }),
  permission({
    key: 'business:settings:integrations-access',
    category: 'Business navigation',
    resource: 'business.settings',
    action: 'integrations-access',
    description: 'Open the integrations settings section',
    riskLevel: 'sensitive',
    displayOrder: 18,
  }),
  permission({
    key: 'business:profile:read',
    category: 'Business account',
    resource: 'business.profile',
    action: 'read',
    description: 'View the business profile',
    riskLevel: 'standard',
    displayOrder: 20,
  }),
  permission({
    key: 'business:profile:update',
    category: 'Business account',
    resource: 'business.profile',
    action: 'update',
    description: 'Update registered business profile fields',
    riskLevel: 'sensitive',
    displayOrder: 30,
    fields: PROFILE_FIELDS,
    supportsApproval: true,
    requiredEntitlement: 'feature.profile_editing',
    quotaKey: 'limit.profile_changes_monthly',
  }),
  permission({
    key: 'business:profile-assets:upload',
    category: 'Business account',
    resource: 'business.profile-assets',
    action: 'upload',
    description: 'Upload business branding assets',
    riskLevel: 'sensitive',
    displayOrder: 40,
    requiredEntitlement: 'feature.branding_editing',
  }),
  permission({
    key: 'business:defaults:read',
    category: 'Business account',
    resource: 'business.defaults',
    action: 'read',
    description: 'View business defaults',
    riskLevel: 'standard',
    displayOrder: 50,
  }),
  permission({
    key: 'business:defaults:update',
    category: 'Business account',
    resource: 'business.defaults',
    action: 'update',
    description: 'Update registered business default fields',
    riskLevel: 'sensitive',
    displayOrder: 60,
    fields: DEFAULT_FIELDS,
    supportsApproval: true,
    requiredEntitlement: 'feature.page_defaults',
  }),
  permission({
    key: 'business:security:email-update',
    category: 'Business account',
    resource: 'business.security',
    action: 'email-update',
    description: 'Update the owner email address',
    riskLevel: 'sensitive',
    displayOrder: 70,
    fields: { email: 'Email address' },
    supportsApproval: true,
  }),
  permission({
    key: 'business:security:username-update',
    category: 'Business account',
    resource: 'business.security',
    action: 'username-update',
    description: 'Change the business owner username',
    riskLevel: 'sensitive',
    displayOrder: 75,
    fields: { username: 'Username' },
    supportsApproval: true,
  }),
  permission({
    key: 'business:security:sessions-revoke',
    category: 'Business account',
    resource: 'business.security',
    action: 'sessions-revoke',
    description: 'Revoke business login sessions',
    riskLevel: 'critical',
    displayOrder: 80,
  }),
  permission({
    key: 'business:templates:browse',
    category: 'Templates',
    resource: 'business.templates',
    action: 'browse',
    description: 'Browse the template catalog',
    riskLevel: 'standard',
    displayOrder: 90,
  }),
  permission({
    key: 'business:templates:use',
    category: 'Templates',
    resource: 'business.templates',
    action: 'use',
    description: 'Use an available template',
    riskLevel: 'standard',
    displayOrder: 100,
  }),
  permission({
    key: 'business:templates:set-default',
    category: 'Templates',
    resource: 'business.templates',
    action: 'set-default',
    description: 'Set the default business template',
    riskLevel: 'sensitive',
    displayOrder: 110,
    supportsApproval: true,
  }),
  permission({
    key: 'business:tiktok:read',
    category: 'TikTok',
    resource: 'business.tiktok',
    action: 'read',
    description: 'View masked TikTok pixel configurations',
    riskLevel: 'standard',
    displayOrder: 120,
    requiredEntitlement: 'feature.tiktok',
  }),
  permission({
    key: 'business:tiktok:create',
    category: 'TikTok',
    resource: 'business.tiktok',
    action: 'create',
    description: 'Create a TikTok pixel configuration',
    riskLevel: 'sensitive',
    displayOrder: 130,
    supportsApproval: true,
    requiredEntitlement: 'feature.tiktok',
    quotaKey: 'limit.tiktok_pixels',
  }),
  permission({
    key: 'business:tiktok:update',
    category: 'TikTok',
    resource: 'business.tiktok',
    action: 'update',
    description: 'Update a TikTok pixel configuration',
    riskLevel: 'sensitive',
    displayOrder: 140,
    fields: {
      pixel_id: 'Pixel ID',
      events_token: 'Events API token',
      display_order: 'Display order',
      status: 'Status',
    },
    supportsApproval: true,
    requiredEntitlement: 'feature.tiktok',
  }),
  permission({
    key: 'business:tiktok:delete',
    category: 'TikTok',
    resource: 'business.tiktok',
    action: 'delete',
    description: 'Delete a TikTok pixel configuration',
    riskLevel: 'critical',
    displayOrder: 150,
    supportsApproval: true,
    requiredEntitlement: 'feature.tiktok',
  }),
  permission({
    key: 'business:tiktok:secret-read',
    category: 'TikTok',
    resource: 'business.tiktok',
    action: 'secret-read',
    description: 'Reveal TikTok Events API tokens',
    riskLevel: 'critical',
    displayOrder: 160,
    requiredEntitlement: 'feature.tiktok',
  }),

  permission({
    key: 'business:linktrees:read',
    category: 'Linktrees',
    resource: 'business.linktrees',
    action: 'read',
    description: 'View linktrees',
    riskLevel: 'standard',
    displayOrder: 200,
  }),
  permission({
    key: 'business:linktrees:create',
    category: 'Linktrees',
    resource: 'business.linktrees',
    action: 'create',
    description: 'Create linktrees',
    riskLevel: 'sensitive',
    displayOrder: 210,
    quotaKey: 'limit.linktrees',
  }),
  permission({
    key: 'business:linktrees:update',
    category: 'Linktrees',
    resource: 'business.linktrees',
    action: 'update',
    description: 'Update registered linktree fields',
    riskLevel: 'sensitive',
    displayOrder: 220,
    fields: LINKTREE_FIELDS,
    supportsApproval: true,
  }),
  permission({
    key: 'business:linktrees:delete',
    category: 'Linktrees',
    resource: 'business.linktrees',
    action: 'delete',
    description: 'Delete linktrees',
    riskLevel: 'critical',
    displayOrder: 230,
    supportsApproval: true,
  }),
  permission({
    key: 'business:linktrees:upload',
    category: 'Linktrees',
    resource: 'business.linktrees',
    action: 'upload',
    description: 'Upload linktree assets',
    riskLevel: 'sensitive',
    displayOrder: 240,
  }),
  permission({
    key: 'business:advertising:read',
    category: 'Advertising',
    resource: 'business.advertising',
    action: 'read',
    description: 'View the advertising service page',
    riskLevel: 'standard',
    displayOrder: 246,
    requiredEntitlement: 'feature.advertising_page',
  }),
  permission({
    key: 'business:advertising:update',
    category: 'Advertising',
    resource: 'business.advertising',
    action: 'update',
    description: 'Edit the advertising service page',
    riskLevel: 'sensitive',
    displayOrder: 247,
    requiredEntitlement: 'feature.advertising_page',
  }),
  permission({
    key: 'business:advertising:publish',
    category: 'Advertising',
    resource: 'business.advertising',
    action: 'publish',
    description: 'Publish or unpublish the advertising service page',
    riskLevel: 'sensitive',
    displayOrder: 248,
    requiredEntitlement: 'feature.advertising_page',
  }),
  permission({
    key: 'business:links:read',
    category: 'Links',
    resource: 'business.links',
    action: 'read',
    description: 'View links',
    riskLevel: 'standard',
    displayOrder: 250,
  }),
  permission({
    key: 'business:links:create',
    category: 'Links',
    resource: 'business.links',
    action: 'create',
    description: 'Create links',
    riskLevel: 'sensitive',
    displayOrder: 260,
  }),
  permission({
    key: 'business:links:update',
    category: 'Links',
    resource: 'business.links',
    action: 'update',
    description: 'Update registered link fields',
    riskLevel: 'sensitive',
    displayOrder: 270,
    fields: LINK_FIELDS,
    supportsApproval: true,
  }),
  permission({
    key: 'business:links:delete',
    category: 'Links',
    resource: 'business.links',
    action: 'delete',
    description: 'Delete links',
    riskLevel: 'critical',
    displayOrder: 280,
    supportsApproval: true,
  }),
  permission({
    key: 'business:links:sync',
    category: 'Links',
    resource: 'business.links',
    action: 'sync',
    description: 'Synchronize a linktree link set',
    riskLevel: 'critical',
    displayOrder: 290,
    supportsApproval: true,
  }),
  permission({
    key: 'business:links:reorder',
    category: 'Links',
    resource: 'business.links',
    action: 'reorder',
    description: 'Reorder links',
    riskLevel: 'sensitive',
    displayOrder: 300,
    fields: { display_order: 'Display order' },
    supportsApproval: true,
  }),

  permission({
    key: 'business:analytics:totals-read',
    category: 'Analytics',
    resource: 'business.analytics',
    action: 'totals-read',
    description: 'View aggregate analytics totals',
    riskLevel: 'standard',
    displayOrder: 350,
  }),
  permission({
    key: 'business:analytics:details-read',
    category: 'Analytics',
    resource: 'business.analytics',
    action: 'details-read',
    description: 'View linktree analytics details',
    riskLevel: 'standard',
    displayOrder: 360,
  }),
  permission({
    key: 'business:analytics:tiktok-health-read',
    category: 'Analytics',
    resource: 'business.analytics',
    action: 'tiktok-health-read',
    description: 'View TikTok delivery diagnostics and retry failed events',
    riskLevel: 'standard',
    displayOrder: 362,
    requiredEntitlement: 'feature.tiktok',
  }),
  permission({
    key: 'business:analytics:clear-linktree',
    category: 'Analytics',
    resource: 'business.analytics',
    action: 'clear-linktree',
    description: 'Clear analytics for one linktree',
    riskLevel: 'critical',
    displayOrder: 390,
    supportsApproval: true,
    requiredEntitlement: 'feature.analytics_clear',
  }),
  permission({
    key: 'business:analytics:clear-all',
    category: 'Analytics',
    resource: 'business.analytics',
    action: 'clear-all',
    description: 'Clear all business analytics',
    riskLevel: 'critical',
    displayOrder: 400,
    supportsApproval: true,
    requiredEntitlement: 'feature.analytics_clear',
  }),

  permission({
    key: 'platform:businesses:read',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'read',
    description: 'View businesses',
    riskLevel: 'standard',
    displayOrder: 500,
  }),
  permission({
    key: 'platform:businesses:create',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'create',
    description: 'Create businesses',
    riskLevel: 'critical',
    displayOrder: 510,
  }),
  permission({
    key: 'platform:businesses:update',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'update',
    description: 'Update businesses',
    riskLevel: 'critical',
    displayOrder: 520,
  }),
  permission({
    key: 'platform:businesses:delete',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'delete',
    description: 'Delete businesses',
    riskLevel: 'critical',
    displayOrder: 530,
  }),
  permission({
    key: 'platform:businesses:sessions-revoke',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'sessions-revoke',
    description: 'Revoke login sessions for a business',
    riskLevel: 'critical',
    displayOrder: 540,
  }),
  permission({
    key: 'platform:businesses:assets-upload',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'assets-upload',
    description: 'Upload business assets',
    riskLevel: 'sensitive',
    displayOrder: 550,
  }),
  permission({
    key: 'platform:businesses:linktrees-read',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'linktrees-read',
    description: 'View business linktrees',
    riskLevel: 'sensitive',
    displayOrder: 560,
  }),
  permission({
    key: 'platform:businesses:linktrees-export',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'linktrees-export',
    description: 'Export business linktrees',
    riskLevel: 'critical',
    displayOrder: 570,
  }),
  permission({
    key: 'platform:businesses:linktrees-import',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'linktrees-import',
    description: 'Import business linktrees',
    riskLevel: 'critical',
    displayOrder: 580,
  }),
  permission({
    key: 'platform:businesses:tiktok-update',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'tiktok-update',
    description: 'Update business TikTok settings',
    riskLevel: 'critical',
    displayOrder: 590,
  }),
  permission({
    key: 'platform:businesses:impersonate',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'impersonate',
    description: 'Open a business dashboard as that business',
    riskLevel: 'critical',
    displayOrder: 600,
  }),
  permission({
    key: 'platform:businesses:profile-requests-read',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'profile-requests-read',
    description: 'View business approval requests',
    riskLevel: 'sensitive',
    displayOrder: 620,
  }),
  permission({
    key: 'platform:businesses:profile-requests-review',
    category: 'Business administration',
    resource: 'platform.businesses',
    action: 'profile-requests-review',
    description: 'Review business approval requests',
    riskLevel: 'critical',
    displayOrder: 630,
  }),

  permission({
    key: 'platform:communications:read',
    category: 'Communication Center',
    resource: 'platform.communications',
    action: 'read',
    description: 'View the Communication Center',
    riskLevel: 'standard',
    displayOrder: 640,
  }),
  permission({
    key: 'platform:communications:announcement-create',
    category: 'Communication Center',
    resource: 'platform.communications',
    action: 'announcement-create',
    description: 'Create and edit communication drafts',
    riskLevel: 'sensitive',
    displayOrder: 650,
  }),
  permission({
    key: 'platform:communications:announcement-publish',
    category: 'Communication Center',
    resource: 'platform.communications',
    action: 'announcement-publish',
    description: 'Publish and schedule announcements',
    riskLevel: 'critical',
    displayOrder: 660,
  }),
  permission({
    key: 'platform:communications:announcement-archive',
    category: 'Communication Center',
    resource: 'platform.communications',
    action: 'announcement-archive',
    description: 'Archive published communication',
    riskLevel: 'sensitive',
    displayOrder: 670,
  }),
  permission({
    key: 'platform:communications:conversation-reply',
    category: 'Communication Center',
    resource: 'platform.communications',
    action: 'conversation-reply',
    description: 'Reply to and manage business conversations',
    riskLevel: 'sensitive',
    displayOrder: 680,
  }),
  permission({
    key: 'platform:communications:homepage-manage',
    category: 'Communication Center',
    resource: 'platform.communications',
    action: 'homepage-manage',
    description: 'Publish public homepage communication',
    riskLevel: 'critical',
    displayOrder: 690,
  }),

  permission({
    key: 'platform:settings:read',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'read',
    description: 'View platform settings',
    riskLevel: 'standard',
    displayOrder: 700,
  }),
  permission({
    key: 'platform:settings:profile-update',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'profile-update',
    description: 'Update the platform administrator profile',
    riskLevel: 'sensitive',
    displayOrder: 710,
  }),
  permission({
    key: 'platform:settings:sessions-revoke',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'sessions-revoke',
    description: 'Manage platform administrator login sessions',
    riskLevel: 'critical',
    displayOrder: 720,
  }),
  permission({
    key: 'platform:settings:branding-update',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'branding-update',
    description: 'Update global branding',
    riskLevel: 'critical',
    displayOrder: 730,
  }),
  permission({
    key: 'platform:settings:tiktok-read',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'tiktok-read',
    description: 'View platform TikTok tracking configuration',
    riskLevel: 'sensitive',
    displayOrder: 728,
  }),
  permission({
    key: 'platform:settings:tiktok-update',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'tiktok-update',
    description: 'Manage platform TikTok tracking configuration',
    riskLevel: 'critical',
    displayOrder: 729,
  }),
  permission({
    key: 'platform:settings:stats-read',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'stats-read',
    description: 'View platform statistics',
    riskLevel: 'sensitive',
    displayOrder: 740,
  }),
  permission({
    key: 'platform:settings:cache-flush',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'cache-flush',
    description: 'Flush application caches',
    riskLevel: 'critical',
    displayOrder: 750,
  }),
  permission({
    key: 'platform:settings:retention-update',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'retention-update',
    description: 'Update operational data retention policy',
    riskLevel: 'critical',
    displayOrder: 755,
  }),
  permission({
    key: 'platform:settings:retention-run',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'retention-run',
    description: 'Run operational data cleanup',
    riskLevel: 'critical',
    displayOrder: 756,
  }),
  permission({
    key: 'platform:settings:media-update',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'media-update',
    description: 'Update platform media and upload policy',
    riskLevel: 'critical',
    displayOrder: 757,
  }),
  permission({
    key: 'platform:settings:media-cleanup',
    category: 'Platform settings',
    resource: 'platform.settings',
    action: 'media-cleanup',
    description: 'Remove unreferenced uploaded media',
    riskLevel: 'critical',
    displayOrder: 758,
  }),
  permission({
    key: 'platform:templates:read',
    category: 'Templates',
    resource: 'platform.templates',
    action: 'read',
    description: 'View global template settings',
    riskLevel: 'standard',
    displayOrder: 760,
  }),
  permission({
    key: 'platform:templates:global-update',
    category: 'Templates',
    resource: 'platform.templates',
    action: 'global-update',
    description: 'Update global template settings',
    riskLevel: 'critical',
    displayOrder: 770,
  }),
  permission({
    key: 'platform:linktrees:read',
    category: 'Platform Linktrees',
    resource: 'platform.linktrees',
    action: 'read',
    description: 'View Sponsor.krd root-domain Linktrees',
    riskLevel: 'standard',
    displayOrder: 772,
  }),
  permission({
    key: 'platform:linktrees:create',
    category: 'Platform Linktrees',
    resource: 'platform.linktrees',
    action: 'create',
    description: 'Create Sponsor.krd root-domain Linktrees',
    riskLevel: 'sensitive',
    displayOrder: 773,
  }),
  permission({
    key: 'platform:linktrees:update',
    category: 'Platform Linktrees',
    resource: 'platform.linktrees',
    action: 'update',
    description: 'Update Sponsor.krd root-domain Linktrees',
    riskLevel: 'sensitive',
    displayOrder: 774,
  }),
  permission({
    key: 'platform:linktrees:delete',
    category: 'Platform Linktrees',
    resource: 'platform.linktrees',
    action: 'delete',
    description: 'Delete Sponsor.krd root-domain Linktrees',
    riskLevel: 'critical',
    displayOrder: 775,
  }),
  permission({
    key: 'platform:linktrees:upload',
    category: 'Platform Linktrees',
    resource: 'platform.linktrees',
    action: 'upload',
    description: 'Upload assets for Sponsor.krd root-domain Linktrees',
    riskLevel: 'sensitive',
    displayOrder: 776,
  }),
  permission({
    key: 'platform:access-control:catalog-read',
    category: 'Access control',
    resource: 'platform.access-control',
    action: 'catalog-read',
    description: 'View the permission catalog',
    riskLevel: 'sensitive',
    displayOrder: 900,
  }),
  permission({
    key: 'platform:access-control:roles-read',
    category: 'Access control',
    resource: 'platform.access-control',
    action: 'roles-read',
    description: 'View roles',
    riskLevel: 'sensitive',
    displayOrder: 910,
  }),
  permission({
    key: 'platform:access-control:roles-create',
    category: 'Access control',
    resource: 'platform.access-control',
    action: 'roles-create',
    description: 'Create roles',
    riskLevel: 'critical',
    displayOrder: 920,
  }),
  permission({
    key: 'platform:access-control:roles-update',
    category: 'Access control',
    resource: 'platform.access-control',
    action: 'roles-update',
    description: 'Update roles',
    riskLevel: 'critical',
    displayOrder: 930,
  }),
  permission({
    key: 'platform:access-control:roles-delete',
    category: 'Access control',
    resource: 'platform.access-control',
    action: 'roles-delete',
    description: 'Delete roles',
    riskLevel: 'critical',
    displayOrder: 940,
  }),
  permission({
    key: 'platform:access-control:simulate',
    category: 'Access control',
    resource: 'platform.access-control',
    action: 'simulate',
    description: 'Simulate authorization decisions',
    riskLevel: 'sensitive',
    displayOrder: 990,
  }),

  permission({
    key: 'platform:billing:entitlements-read',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'entitlements-read',
    description: 'View entitlements',
    riskLevel: 'sensitive',
    displayOrder: 1000,
  }),
  permission({
    key: 'platform:billing:entitlements-create',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'entitlements-create',
    description: 'Create entitlements',
    riskLevel: 'critical',
    displayOrder: 1010,
  }),
  permission({
    key: 'platform:billing:entitlements-update',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'entitlements-update',
    description: 'Update entitlements',
    riskLevel: 'critical',
    displayOrder: 1020,
  }),
  permission({
    key: 'platform:billing:plans-read',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'plans-read',
    description: 'View subscription plans',
    riskLevel: 'sensitive',
    displayOrder: 1030,
  }),
  permission({
    key: 'platform:billing:plans-create',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'plans-create',
    description: 'Create subscription plans',
    riskLevel: 'critical',
    displayOrder: 1040,
  }),
  permission({
    key: 'platform:billing:plans-update',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'plans-update',
    description: 'Update subscription plans',
    riskLevel: 'critical',
    displayOrder: 1050,
  }),
  permission({
    key: 'platform:billing:subscriptions-read',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'subscriptions-read',
    description: 'View subscriptions',
    riskLevel: 'sensitive',
    displayOrder: 1080,
  }),
  permission({
    key: 'platform:billing:subscriptions-assign',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'subscriptions-assign',
    description: 'Assign subscriptions',
    riskLevel: 'critical',
    displayOrder: 1090,
  }),
  permission({
    key: 'platform:billing:usage-read',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'usage-read',
    description: 'View quota usage',
    riskLevel: 'sensitive',
    displayOrder: 1150,
  }),
  permission({
    key: 'platform:billing:approvals-read',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'approvals-read',
    description: 'View approval requests',
    riskLevel: 'sensitive',
    displayOrder: 1160,
  }),
  permission({
    key: 'platform:billing:approvals-review',
    category: 'Billing',
    resource: 'platform.billing',
    action: 'approvals-review',
    description: 'Approve or reject permission requests',
    riskLevel: 'critical',
    displayOrder: 1170,
  }),
] as const;

type CatalogDefinition = (typeof ALL_PERMISSION_DEFINITIONS)[number];
type BusinessPermissionDefinition = Extract<
  CatalogDefinition,
  { readonly key: `business:${string}` }
>;

export const PERMISSION_CATALOG: readonly BusinessPermissionDefinition[] =
  ALL_PERMISSION_DEFINITIONS.filter(
    (item): item is BusinessPermissionDefinition =>
      item.key.startsWith('business:'),
  );

export type PermissionKey = (typeof PERMISSION_CATALOG)[number]['key'];

export const PERMISSION_BY_KEY = new Map<PermissionKey, PermissionDefinition>(
  PERMISSION_CATALOG.map((item) => [item.key, item]),
);

export function isPermissionKey(value: string): value is PermissionKey {
  return PERMISSION_BY_KEY.has(value as PermissionKey);
}

export const Capability = {
  BusinessDashboardView: 'business:dashboard:view',
  BusinessPagesLinktreesAccess: 'business:pages:linktrees-access',
  BusinessPagesTemplatesAccess: 'business:pages:templates-access',
  BusinessPagesProfileAccess: 'business:pages:profile-access',
  BusinessPagesSettingsAccess: 'business:pages:settings-access',
  BusinessPagesAdvertisingAccess: 'business:pages:advertising-access',
  BusinessSettingsProfileAccess: 'business:settings:profile-access',
  BusinessSettingsDefaultsAccess: 'business:settings:defaults-access',
  BusinessSettingsSecurityAccess: 'business:settings:security-access',
  BusinessSettingsIntegrationsAccess: 'business:settings:integrations-access',
  BusinessProfileRead: 'business:profile:read',
  BusinessProfileUpdate: 'business:profile:update',
  BusinessProfileAssetsUpload: 'business:profile-assets:upload',
  BusinessDefaultsRead: 'business:defaults:read',
  BusinessDefaultsUpdate: 'business:defaults:update',
  BusinessSecurityEmailUpdate: 'business:security:email-update',
  BusinessSecurityUsernameUpdate: 'business:security:username-update',
  BusinessSecuritySessionsRevoke: 'business:security:sessions-revoke',
  BusinessTemplatesBrowse: 'business:templates:browse',
  BusinessTemplatesUse: 'business:templates:use',
  BusinessTemplatesSetDefault: 'business:templates:set-default',
  BusinessTikTokRead: 'business:tiktok:read',
  BusinessTikTokCreate: 'business:tiktok:create',
  BusinessTikTokUpdate: 'business:tiktok:update',
  BusinessTikTokDelete: 'business:tiktok:delete',
  BusinessTikTokSecretRead: 'business:tiktok:secret-read',
  BusinessLinktreesRead: 'business:linktrees:read',
  BusinessLinktreesCreate: 'business:linktrees:create',
  BusinessLinktreesUpdate: 'business:linktrees:update',
  BusinessLinktreesDelete: 'business:linktrees:delete',
  BusinessLinktreesUpload: 'business:linktrees:upload',
  BusinessAdvertisingRead: 'business:advertising:read',
  BusinessAdvertisingUpdate: 'business:advertising:update',
  BusinessAdvertisingPublish: 'business:advertising:publish',
  BusinessLinksRead: 'business:links:read',
  BusinessLinksCreate: 'business:links:create',
  BusinessLinksUpdate: 'business:links:update',
  BusinessLinksDelete: 'business:links:delete',
  BusinessLinksSync: 'business:links:sync',
  BusinessLinksReorder: 'business:links:reorder',
  BusinessAnalyticsTotalsRead: 'business:analytics:totals-read',
  BusinessAnalyticsDetailsRead: 'business:analytics:details-read',
  BusinessAnalyticsTikTokHealthRead: 'business:analytics:tiktok-health-read',
  BusinessAnalyticsClearLinktree: 'business:analytics:clear-linktree',
  BusinessAnalyticsClearAll: 'business:analytics:clear-all',
  PlatformBusinessesRead: 'platform:businesses:read',
  PlatformBusinessesCreate: 'platform:businesses:create',
  PlatformBusinessesUpdate: 'platform:businesses:update',
  PlatformBusinessesDelete: 'platform:businesses:delete',
  PlatformBusinessesSessionsRevoke: 'platform:businesses:sessions-revoke',
  PlatformBusinessesAssetsUpload: 'platform:businesses:assets-upload',
  PlatformBusinessesLinktreesRead: 'platform:businesses:linktrees-read',
  PlatformBusinessesLinktreesExport: 'platform:businesses:linktrees-export',
  PlatformBusinessesLinktreesImport: 'platform:businesses:linktrees-import',
  PlatformBusinessesTikTokUpdate: 'platform:businesses:tiktok-update',
  PlatformBusinessesImpersonate: 'platform:businesses:impersonate',
  PlatformBusinessesProfileRequestsRead:
    'platform:businesses:profile-requests-read',
  PlatformBusinessesProfileRequestsReview:
    'platform:businesses:profile-requests-review',
  PlatformCommunicationsRead: 'platform:communications:read',
  PlatformCommunicationsAnnouncementCreate:
    'platform:communications:announcement-create',
  PlatformCommunicationsAnnouncementPublish:
    'platform:communications:announcement-publish',
  PlatformCommunicationsAnnouncementArchive:
    'platform:communications:announcement-archive',
  PlatformCommunicationsConversationReply:
    'platform:communications:conversation-reply',
  PlatformCommunicationsHomepageManage:
    'platform:communications:homepage-manage',
  PlatformSettingsRead: 'platform:settings:read',
  PlatformSettingsProfileUpdate: 'platform:settings:profile-update',
  PlatformSettingsSessionsRevoke: 'platform:settings:sessions-revoke',
  PlatformSettingsBrandingUpdate: 'platform:settings:branding-update',
  PlatformSettingsStatsRead: 'platform:settings:stats-read',
  PlatformSettingsCacheFlush: 'platform:settings:cache-flush',
  PlatformSettingsRetentionUpdate: 'platform:settings:retention-update',
  PlatformSettingsRetentionRun: 'platform:settings:retention-run',
  PlatformSettingsMediaUpdate: 'platform:settings:media-update',
  PlatformSettingsMediaCleanup: 'platform:settings:media-cleanup',
  PlatformSettingsTikTokRead: 'platform:settings:tiktok-read',
  PlatformSettingsTikTokUpdate: 'platform:settings:tiktok-update',
  PlatformTemplatesRead: 'platform:templates:read',
  PlatformTemplatesGlobalUpdate: 'platform:templates:global-update',
  PlatformLinktreesRead: 'platform:linktrees:read',
  PlatformLinktreesCreate: 'platform:linktrees:create',
  PlatformLinktreesUpdate: 'platform:linktrees:update',
  PlatformLinktreesDelete: 'platform:linktrees:delete',
  PlatformLinktreesUpload: 'platform:linktrees:upload',
  PlatformAccessControlCatalogRead: 'platform:access-control:catalog-read',
  PlatformAccessControlRolesRead: 'platform:access-control:roles-read',
  PlatformAccessControlRolesCreate: 'platform:access-control:roles-create',
  PlatformAccessControlRolesUpdate: 'platform:access-control:roles-update',
  PlatformAccessControlRolesDelete: 'platform:access-control:roles-delete',
  PlatformAccessControlSimulate: 'platform:access-control:simulate',
  PlatformBillingEntitlementsRead: 'platform:billing:entitlements-read',
  PlatformBillingEntitlementsCreate: 'platform:billing:entitlements-create',
  PlatformBillingEntitlementsUpdate: 'platform:billing:entitlements-update',
  PlatformBillingPlansRead: 'platform:billing:plans-read',
  PlatformBillingPlansCreate: 'platform:billing:plans-create',
  PlatformBillingPlansUpdate: 'platform:billing:plans-update',
  PlatformBillingSubscriptionsRead: 'platform:billing:subscriptions-read',
  PlatformBillingSubscriptionsAssign: 'platform:billing:subscriptions-assign',
  PlatformBillingUsageRead: 'platform:billing:usage-read',
  PlatformBillingApprovalsRead: 'platform:billing:approvals-read',
  PlatformBillingApprovalsReview: 'platform:billing:approvals-review',
} as const;

export type Capability = (typeof Capability)[keyof typeof Capability];
