import type { TikTokCampaign } from "./types";
import { buildTikTokApiPayload } from "./tiktok-payload-builder";

export const INITIAL_MOCK_CAMPAIGNS: TikTokCampaign[] = [
  {
    id: "camp-001",
    name: "کەمپەینی بەهار ٢٠٢٦ - ڕیکلامی تایبەت",
    video: {
      title: "spring-launch-v3.mp4",
      duration: "00:18",
      format: "9:16",
      resolution: "1080 × 1920",
      tone: "cyan",
    },
    objective: "REACH",
    status: "active",
    dailyBudget: 25.0,
    totalSpent: 165.4,
    impressions: 48920,
    clicks: 3410,
    ctr: 6.97,
    cpc: 0.048,
    conversions: 245,
    destinationPage: {
      id: "lt-1",
      title: "لاپەڕەی سەرەکی براند",
      slug: "main",
      type: "linktree",
      url: "https://sponsor.krd/main",
    },
    targetAudience: {
      location: "هەولێر، سلێمانی، دهۆک",
      gender: "ALL",
      ageGroups: ["18-24", "25-34"],
      languages: ["Kurdish", "Arabic", "English"],
    },
    callToAction: "سەردانی وێبسایت بکە",
    setup: {
      optimizationGoal: "REACH",
      bidStrategy: "MAXIMIZE_DELIVERY",
      scheduleType: "START_NOW",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/main",
      videoCode: "TIKTOK_SPARK_CODE_SPRING",
      adText: "کۆکراوەی سەرجەم بەستەرەکان لە یەک شوێن",
    },
    tiktokPayload: buildTikTokApiPayload({
      campaignName: "کەمپەینی بەهار ٢٠٢٦ - ڕیکلامی تایبەت",
      objective: "REACH",
      optimizationGoal: "REACH",
      dataConnectionId: "",
      optimizationEvent: "",
      bidStrategy: "MAXIMIZE_DELIVERY",
      dailyBudget: 25.0,
      scheduleType: "START_NOW",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
      location: "هەولێر، سلێمانی، دهۆک",
      gender: "ALL",
      ageGroups: ["18-24", "25-34"],
      languages: "Kurdish, Arabic, English",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/main",
      videoCode: "TIKTOK_SPARK_CODE_SPRING",
      adText: "کۆکراوەی سەرجەم بەستەرەکان لە یەک شوێن",
      callToAction: "LEARN_MORE",
      interactiveAddOnEnabled: false,
      addOnMode: "CREATE",
      newAddOnType: "",
      existingAddOnId: "",
    }),
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-06T14:30:00Z",
  },
  {
    id: "camp-002",
    name: "پڕۆمۆی بەرهەمی نوێ و داشکاندن",
    video: {
      title: "monthly-offer.mp4",
      duration: "00:24",
      format: "9:16",
      resolution: "1080 × 1920",
      tone: "violet",
    },
    objective: "SALES",
    status: "active",
    dailyBudget: 40.0,
    totalSpent: 280.0,
    impressions: 72150,
    clicks: 4620,
    ctr: 6.4,
    cpc: 0.06,
    conversions: 412,
    destinationPage: {
      id: "lt-2",
      title: "داشکاندنەکانی ئەم مانگە",
      slug: "offers",
      type: "linktree",
      url: "https://sponsor.krd/offers",
    },
    targetAudience: {
      location: "کوردستان و سەرجەم عێراق",
      gender: "ALL",
      ageGroups: ["18-24", "25-34", "35-44"],
      languages: ["Kurdish", "Arabic"],
    },
    callToAction: "ئێستا داوا بکە",
    setup: {
      optimizationGoal: "CONVERSIONS",
      dataConnectionId: "sponsor-krd-main",
      optimizationEvent: "Purchase",
      bidStrategy: "MAXIMIZE_DELIVERY",
      scheduleType: "START_NOW",
      startDate: "2026-02-25",
      endDate: "2026-03-25",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/offers",
      videoCode: "TIKTOK_SPARK_CODE_OFFERS",
      adText: "داشکاندنی وەرزی تایبەت بۆ بەشداربووان",
    },
    tiktokPayload: buildTikTokApiPayload({
      campaignName: "پڕۆمۆی بەرهەمی نوێ و داشکاندن",
      objective: "SALES",
      optimizationGoal: "CONVERSIONS",
      dataConnectionId: "sponsor-krd-main",
      optimizationEvent: "Purchase",
      bidStrategy: "MAXIMIZE_DELIVERY",
      dailyBudget: 40.0,
      scheduleType: "START_NOW",
      startDate: "2026-02-25",
      endDate: "2026-03-25",
      location: "کوردستان و سەرجەم عێراق",
      gender: "ALL",
      ageGroups: ["18-24", "25-34", "35-44"],
      languages: "Kurdish, Arabic",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/offers",
      videoCode: "TIKTOK_SPARK_CODE_OFFERS",
      adText: "داشکاندنی وەرزی تایبەت بۆ بەشداربووان",
      callToAction: "ORDER_NOW",
      interactiveAddOnEnabled: false,
      addOnMode: "CREATE",
      newAddOnType: "",
      existingAddOnId: "",
    }),
    createdAt: "2026-02-25T12:00:00Z",
    updatedAt: "2026-03-05T18:15:00Z",
  },
  {
    id: "camp-003",
    name: "ناساندنی خزمەتگوزارییەکان بۆ کۆمپانیاکان",
    video: {
      title: "business-services.mp4",
      duration: "00:31",
      format: "1:1",
      resolution: "1080 × 1080",
      tone: "orange",
    },
    objective: "WEBSITE_LEAD",
    status: "paused",
    dailyBudget: 15.0,
    totalSpent: 94.2,
    impressions: 21400,
    clicks: 1120,
    ctr: 5.23,
    cpc: 0.084,
    conversions: 68,
    destinationPage: {
      id: "lt-3",
      title: "خزمەتگوزاری بازرگانی",
      slug: "b2b",
      type: "linktree",
      url: "https://sponsor.krd/b2b",
    },
    targetAudience: {
      location: "هەولێر و بەغدا",
      gender: "ALL",
      ageGroups: ["25-34", "35-44", "45-54"],
      languages: ["Kurdish", "Arabic", "English"],
    },
    callToAction: "پەیوەندیمان پێوە بکە",
    setup: {
      optimizationGoal: "LEADS",
      dataConnectionId: "ismail-cs",
      optimizationEvent: "Contact",
      bidStrategy: "MAXIMIZE_DELIVERY",
      scheduleType: "START_NOW",
      startDate: "2026-02-10",
      endDate: "2026-03-10",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/b2b",
      videoCode: "TIKTOK_SPARK_CODE_B2B",
      adText: "پەیوەندی بکە بە باشترین خزمەتگوزاری بازرگانی",
    },
    tiktokPayload: buildTikTokApiPayload({
      campaignName: "ناساندنی خزمەتگوزارییەکان بۆ کۆمپانیاکان",
      objective: "WEBSITE_LEAD",
      optimizationGoal: "LEADS",
      dataConnectionId: "ismail-cs",
      optimizationEvent: "Contact",
      bidStrategy: "MAXIMIZE_DELIVERY",
      dailyBudget: 15.0,
      scheduleType: "START_NOW",
      startDate: "2026-02-10",
      endDate: "2026-03-10",
      location: "هەولێر و بەغدا",
      gender: "ALL",
      ageGroups: ["25-34", "35-44", "45-54"],
      languages: "Kurdish, Arabic, English",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/b2b",
      videoCode: "TIKTOK_SPARK_CODE_B2B",
      adText: "پەیوەندی بکە بە باشترین خزمەتگوزاری بازرگانی",
      callToAction: "CONTACT_US",
      interactiveAddOnEnabled: false,
      addOnMode: "CREATE",
      newAddOnType: "",
      existingAddOnId: "",
    }),
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-03-04T11:20:00Z",
  },
  {
    id: "camp-004",
    name: "ڕیکلامی ڤیدیۆیی - بینینی پەیج",
    video: {
      title: "brand-awareness-final.mp4",
      duration: "00:15",
      format: "9:16",
      resolution: "1080 × 1920",
      tone: "rose",
    },
    objective: "VIDEO_VIEWS",
    status: "review",
    dailyBudget: 20.0,
    totalSpent: 0.0,
    impressions: 0,
    clicks: 0,
    ctr: 0.0,
    cpc: 0.0,
    conversions: 0,
    destinationPage: {
      id: "lt-1",
      title: "لاپەڕەی سەرەکی براند",
      slug: "main",
      type: "linktree",
      url: "https://sponsor.krd/main",
    },
    targetAudience: {
      location: "سەرجەم کوردستان",
      gender: "ALL",
      ageGroups: ["18-24", "25-34"],
      languages: ["Kurdish"],
    },
    callToAction: "سەردان بکە",
    setup: {
      optimizationGoal: "VIDEO_VIEW_IN_6S",
      bidStrategy: "MAXIMIZE_DELIVERY",
      scheduleType: "START_NOW",
      startDate: "2026-03-06",
      endDate: "2026-04-06",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/main",
      videoCode: "TIKTOK_SPARK_CODE_AWARENESS",
      adText: "ڕیکلامی نوێی بینەرانی تیکتۆک",
    },
    tiktokPayload: buildTikTokApiPayload({
      campaignName: "ڕیکلامی ڤیدیۆیی - بینینی پەیج",
      objective: "VIDEO_VIEWS",
      optimizationGoal: "VIDEO_VIEW_IN_6S",
      dataConnectionId: "",
      optimizationEvent: "",
      bidStrategy: "MAXIMIZE_DELIVERY",
      dailyBudget: 20.0,
      scheduleType: "START_NOW",
      startDate: "2026-03-06",
      endDate: "2026-04-06",
      location: "سەرجەم کوردستان",
      gender: "ALL",
      ageGroups: ["18-24", "25-34"],
      languages: "Kurdish",
      placement: "TIKTOK_ONLY",
      destinationUrl: "https://sponsor.krd/main",
      videoCode: "TIKTOK_SPARK_CODE_AWARENESS",
      adText: "ڕیکلامی نوێی بینەرانی تیکتۆک",
      callToAction: "WATCH_NOW",
      interactiveAddOnEnabled: false,
      addOnMode: "CREATE",
      newAddOnType: "",
      existingAddOnId: "",
    }),
    createdAt: "2026-03-06T08:00:00Z",
    updatedAt: "2026-03-06T08:00:00Z",
  },
];

export const OBJECTIVE_LABELS: Record<
  string,
  { label: string; description: string }
> = {
  REACH: {
    label: "Reach",
    description: "گەیاندنی ڕیکلامەکە بە زۆرترین ژمارەی بینەری گونجاو",
  },
  VIDEO_VIEWS: {
    label: "Video Views",
    description: "زیادکردنی بینین و سەیرکردنی ڤیدیۆی ڕیکلامەکەت",
  },
  WEBSITE_LEAD: {
    label: "Website Lead",
    description: "کۆکردنەوەی پەیوەندی و ژمارەی کڕیارە شیاوەکان",
  },
  SALES: {
    label: "Sales",
    description: "زیادکردنی فرۆشتن و گۆڕان لە ڕێگەی وێبسایتەکەتەوە",
  },
};
